# Generated by Django 5.0.6 on 2024-06-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News_app', '0002_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category_type',
            field=models.CharField(choices=[('NE', 'Новость'), ('AR', 'Статья')], default='NE', max_length=2),
        ),
    ]
